# Generated by Django 4.2.6 on 2023-10-21 11:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('holder_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('matric_no', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('grade', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='certapp.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='certapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('cert_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certapp.holder')),
            ],
        ),
    ]
