# Generated by Django 4.2.6 on 2023-10-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holder',
            name='course',
        ),
    ]
