# Generated by Django 4.2.6 on 2023-10-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certapp', '0003_alter_certificate_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='qr_code',
            field=models.TextField(default='code'),
            preserve_default=False,
        ),
    ]
