# Generated by Django 4.2.6 on 2023-10-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certapp', '0007_alter_holder_matric_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='picture',
            field=models.ImageField(default='auth/assets/images/default.jpg', upload_to='uploads/'),
        ),
    ]
