# Generated by Django 4.2.6 on 2023-10-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certapp', '0008_holder_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='level',
            field=models.CharField(choices=[('national diploma', 'national diploma'), ('higher national diploma', 'higher national diploma')], default='national diploma', max_length=50),
        ),
    ]
