# Generated by Django 4.2.6 on 2023-10-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certapp', '0009_holder_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rector', models.ImageField(upload_to='uploads/signature/')),
                ('registrar', models.ImageField(upload_to='uploads/signature/')),
            ],
        ),
    ]
